remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
description: >
  <p>Professional Website & Data Science Portfolio</p>
  <p>
    <a href="index.html" class="btn">Home</a>
    <a href="data_science_skills.html" class="btn">Data Science Skills</a>
    <a href="https://github.com/holland-reece" class="btn">GitHub</a>
    <a href="https://www.linkedin.com/in/holland-reece-brown-9bb719263" class="btn">LinkedIn</a>   
  </p>