remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Holland Reece Brown
logo: /images/logo_v1.png
description: >
  <p>Professional Website & Data Science Portfolio</p>
  <p><a href="index.html" class="btn">Home</a></p>
  <p><a href="technical_skills.html" class="btn">Technical Skills</a></p>
  <p><a href="data_science_skills.html" class="btn">Data Science Portfolio</a></p>
  <p><a href="https://www.linkedin.com/in/holland-reece-brown-9bb719263" class="btn">LinkedIn</a></p>
